[project]
name = "kiln-root"
version = "0.1.1"
description = "uv workspace project for Kiln AI. See kiln-ai package on pypi for our library (libs/core)"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "kiln-ai==0.5.3",
    "kiln-server",
    "kiln-studio-desktop",
]

[dependency-groups]
dev = [
    "isort>=5.13.2",
    "pyright==1.1.376",
    "pytest-asyncio>=0.24.0",
    "pytest>=8.3.3",
    "pytest-xdist>=3.5",
    "python-dotenv>=1.0.1",
    "ruff>=0.9.0",
]



[tool.uv]
# While Together depends on pyarrow, it doesn't need it, it's 80MB, and it doesn't work on MacOS 11
override-dependencies = [
    "pyarrow ; sys_platform == 'never'",
]

[tool.uv.workspace]
members = ["libs/core", "libs/server", "app/desktop"]

[tool.uv.sources]
kiln-server = { workspace = true }
kiln-studio-desktop = { workspace = true }
kiln-ai = { workspace = true }

[tool.pyright]
strictListInference = true
reportMissingTypeArgument = true


[tool.ruff]
exclude = [
]

[tool.pytest.ini_options]
 addopts="-n auto"
